In [1]:
import numpy as np
from sklearn.linear_model import LinearRegression

In [2]:
# Create a feature matrix with two features
X = np.array([[1, 1], [1, 2], [2, 2], [2, 3], [3, 4], [4, 2], [5, 5], [6, 3], [7, 1]])

# Define the target variable as a linear combination of features plus a bias term
# y = 1 * x_0 + 2 * x_1 + 3
y = np.dot(X, np.array([1, 2])) + 3

In [3]:
X

array([[1, 1],
       [1, 2],
       [2, 2],
       [2, 3],
       [3, 4],
       [4, 2],
       [5, 5],
       [6, 3],
       [7, 1]])

In [4]:
X.shape

(9, 2)

In [5]:
y

array([ 6,  8,  9, 11, 14, 11, 18, 15, 12])

In [6]:
# Initialize a Linear Regression model and fit it to the data

reg = LinearRegression().fit(X, y)
reg.score(X, y)

1.0

In [7]:
# Display the coefficients of the linear model

reg.coef_

array([1., 2.])

In [8]:
# Display the intercept of the linear model

reg.intercept_

3.0000000000000018

y = 3 + 1x1 + 2x2

In [9]:
reg.predict(np.array([[3, 5]]))

array([16.])